language: node_js

node_js:
  - "10.15.3"
  - "11.0.0"
yarn:
  - "1.13.0"

before_script:
  - npm global add selenium-standalone@latest
  - selenium-standalone install
  - selenium-standalone start &
  - sleep 5