language: node_js

node_js:
  - "7.0.0"
  - "7.4.0"
  - "8.0.0"
  - "8.4.0"

before_script:
  - npm install selenium-standalone@latest -g
  - selenium-standalone install
  - selenium-standalone start &
  - sleep 5
