language: node_js
node_js:
  - "6.7.0"
  - "6.9.0"
  - "7.0.0"
  - "7.4.0"
  - "8.0.0"
  - "8.4.0"
before_script:
  - npm install selenium-standalone@latest -g
  - selenium-standalone install
  - nohup selenium-standalone start > selenium.txt 2>&1 </dev/null &
#
#before_install:
#    - export CHROME_BIN=/usr/bin/google-chrome
#    - export DISPLAY=:99.0
#    - sh -e /etc/init.d/xvfb start
#    - sudo apt-get update
#    - sudo apt-get install -y libappindicator1 fonts-liberation
#    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
#    - sudo dpkg -i google-chrome*.deb

      